### ISSUE TITLE
Problem: line breaks are needed before section headers

### ISSUE THREAD

**Issue by peterVG** [artefactual-labs/testing-checklists#12]
See for example Test 1.7, the header for the next section and its markup (## 2 - Transfer Variants) is appended to the last 1.7 checklist item instead of starting on a new line as a header for the next section. The same is true for other section headers (e.g. see 2.12, 3.2, 5.3 etc). N.B. the header for Section 5 is displayed correctly.

**Comment by sallain** [comment]
This is just a markdown formatting issue, not an issue with the spreadsheet.
