### ISSUE TITLE
Problem: multi-level CSV sample data only contains one directory

### ISSUE THREAD

**Issue by peterVG** [artefactual-labs/testing-checklists#14]
In test 2.3 the checklist reads "The AIP METS contains descriptive metadata for *each* of the directories described in the metadata.csv". However, the sample data only contains one directory. 
See https://github.com/artefactual/archivematica-sampledata/blob/master/SampleTransfers/CSVmultiLevel/metadata/metadata.csv
We should add additional directories to check for in the sample data or re-write the checklist to something like "The AIP METS contains descriptive metadata for the directory and the items in it."

**Comment by sallain** [comment]
Giving the multi-level CSV sampledata more levels would be useful and can be done via a PR to the sampledata. Meanwhile I think this test is still accurate ("each" can equal 1) so I'm going to leave it.
