### ISSUE TITLE
Problem: update 2.8 and 2.9 with instructions on which sample transfers to use (transfers with processingMCP.xml files)

### ISSUE THREAD

**Issue by peterVG** [artefactual-labs/testing-checklists#18]
Currently Test 2.9 requires the tester to create and upload their own zipped bag of test data with a processingMCP.xml. This can lead to human/technical errors whereas sampledata for this test already exists. It just needs to be pushed to the testing VMs when they are generated: https://github.com/artefactual/archivematica-sampledata/blob/master/SampleTransfers/BagExamples/ZippedBags/SimpleBagWithProcessingMCP.zip

**Comment by peterVG** [comment]
The following zipped bag can also be used: [BagitWithProcessingMCP.zip](https://github.com/archivematica/testing-checklists/files/4309606/BagitWithProcessingMCP.zip)

It stops for decision points at: Examine Contents, Normalize, and Store AIP. All other decision points are skipped.

**Comment by sallain** [comment]
@peterVG just updating the title here to indicate that the checklist should be changed to use the new sampledata transfers; I've asked @mamedin directly to update the sampledata.
