### ISSUE TITLE
Problem: For use in test 5.3, "SampleTransfers/DiactricsTest" directory does not exist

### ISSUE THREAD

**Issue by peterVG** [artefactual-labs/testing-checklists#20]
Test 5.3 instructs the use of "SampleTransfers/DiacriticsTest" as sample data but this directory does not exist in the sampledata repository:
https://github.com/artefactual/archivematica-sampledata/tree/master/SampleTransfers

**Comment by sallain** [comment]
I have added this transfer https://github.com/artefactual/archivematica-sampledata/commit/8774133b1922f93015d4e40c8ec13bdf06dbd864
